default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.values_at('WEB_CONCURRENCY', 'RAILS_MAX_THREADS').map { |i| i || 1 }.inject(&:*) %>

development:
  <<: *default
  database: applied_history_development
test:
  <<: *default
  database: applied_history_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
